phases:

  - name: p1
    town: Town01
    weather: ClearNoon
    traffic: 0
    target_step: 1000000

  - name: p2
    town: Town01
    weather: ClearNoon
    traffic: 10
    target_step: 1700000

  - name: p3
    town: Town03
    weather: ClearNoon
    traffic: 0
    target_step: 2500000

  - name: p4
    town: Town03
    weather: ClearNoon
    traffic: 10
    target_step: 3500000
