phases:

  - until_step: 1000000
    towns: ["Town01"]
    weather: ["ClearNoon"]
    traffic: 0

  - until_step: 3000000
    towns: ["Town01","Town03"]
    weather: ["ClearNoon","CloudyNoon","WetNoon"]
    traffic: 20

  - until_step: 5000000
    towns: ["Town01","Town02","Town03","Town05"]
    weather: ["ClearNoon","CloudyNoon","WetNoon","SoftRainNoon"]
    traffic: 50